//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_21_22
{
    using System;
    using System.Collections.Generic;
    
    public partial class InCome
    {
        public int InvoiceNumber { get; set; }
        public int IdProduct { get; set; }
        public int QuantityInCome { get; set; }
        public System.DateTime DateInComing { get; set; }
    
        public virtual PriceTag PriceTag { get; set; }
    }
}
