//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_21_22
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int IdShipper { get; set; }
        public int IdProduct { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
    
        public virtual PriceTag PriceTag { get; set; }
    }
}
