//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_21_22
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseStockEntities : DbContext
    {
        public BaseStockEntities()
            : base("name=BaseStockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InCome> InComes { get; set; }
        public virtual DbSet<PriceTag> PriceTags { get; set; }
        public virtual DbSet<ProductGroupDirectory> ProductGroupDirectories { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
    }
}
